import pg from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const connectionString = process.env.DATABASE_URL;

console.log("Connecting to Neon PostgreSQL database for initialization...");

const pool = new pg.Pool({
  connectionString,
  ssl: {
    rejectUnauthorized: false
  }
});

async function initDatabase() {
  let client;
  try {
    client = await pool.connect();
    console.log("✓ Connected to Neon PostgreSQL!");

    // 1. Create stores table
    await client.query(`
      CREATE TABLE IF NOT EXISTS stores (
        store_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        store_name VARCHAR(100) NOT NULL UNIQUE,
        CONSTRAINT chk_store_name_length CHECK (char_length(TRIM(store_name)) >= 2),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log("✓ stores table ready.");

    // 2. Create products table (multi-tenant scoped with exact requested variables)
    await client.query(`
      CREATE TABLE IF NOT EXISTS products (
        product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        product_name VARCHAR(255) NOT NULL,
        unit_price NUMERIC(10,2) NOT NULL,
        current_stock_level INTEGER NOT NULL,
        minimum_stock_threshold INTEGER DEFAULT 5,
        last_updated_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        category VARCHAR(100) NOT NULL,
        description TEXT,
        images TEXT[],
        photos TEXT[],
        UNIQUE (store_id, product_name)
      );
    `);
    
    // Dynamic self-healing column check and alteration
    const columnCheck = await client.query(`
      SELECT column_name FROM information_schema.columns WHERE table_name = 'products';
    `);
    const cols = columnCheck.rows.map(r => r.column_name);

    if (cols.includes('name') && !cols.includes('product_name')) {
      await client.query("ALTER TABLE products RENAME COLUMN name TO product_name;");
    }
    if (cols.includes('price') && !cols.includes('unit_price')) {
      await client.query("ALTER TABLE products RENAME COLUMN price TO unit_price;");
    }
    if (cols.includes('stock') && !cols.includes('current_stock_level')) {
      await client.query("ALTER TABLE products RENAME COLUMN stock TO current_stock_level;");
    }

    // Alter existing products table for new requested columns
    await client.query(`
      ALTER TABLE products ADD COLUMN IF NOT EXISTS store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE;
      ALTER TABLE products ADD COLUMN IF NOT EXISTS photos TEXT[];
      ALTER TABLE products ADD COLUMN IF NOT EXISTS minimum_stock_threshold INTEGER DEFAULT 5;
      ALTER TABLE products ADD COLUMN IF NOT EXISTS last_updated_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
      ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2) DEFAULT 0;
      ALTER TABLE products DROP CONSTRAINT IF EXISTS products_name_key;
      ALTER TABLE products DROP CONSTRAINT IF EXISTS uq_store_product;
      ALTER TABLE products ADD CONSTRAINT uq_store_product UNIQUE (store_id, product_name);
    `);
    console.log("✓ products table ready with exact multi-tenant variables (incl. cost_price).");

    // 3. Create transactions table (multi-tenant scoped)
    await client.query(`
      CREATE TABLE IF NOT EXISTS transactions (
        transaction_id VARCHAR(100) PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        client_name VARCHAR(100) NOT NULL,
        amount NUMERIC(10,2) NOT NULL,
        method VARCHAR(100) NOT NULL,
        status VARCHAR(50) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
      );
    `);
    
    // Alter existing transactions table to add store_id scoping + product linking
    await client.query(`
      ALTER TABLE transactions ADD COLUMN IF NOT EXISTS store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE;
      ALTER TABLE transactions ADD COLUMN IF NOT EXISTS product_id INTEGER REFERENCES products(product_id) ON DELETE SET NULL;
      ALTER TABLE transactions ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1;
    `);
    console.log("✓ transactions table ready with store_id scoping + product_id/quantity linking.");

    // 4. Create distributors table
    await client.query(`
      CREATE TABLE IF NOT EXISTS distributors (
        distributor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        distributor_name VARCHAR(100) NOT NULL UNIQUE,
        contact_email VARCHAR(100) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log("✓ distributors table ready.");

    // 5. Drop and recreate distributor_orders table to match requested schema exactly
    await client.query("DROP TABLE IF EXISTS distributor_orders CASCADE;");
    await client.query(`
      CREATE TABLE distributor_orders (
        distributor_order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        distributor_id INTEGER REFERENCES distributors(distributor_id) ON DELETE CASCADE,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        ordered_items_list JSONB NOT NULL,
        order_status VARCHAR(50) NOT NULL DEFAULT 'Pending' CONSTRAINT chk_order_status CHECK (order_status IN ('Pending', 'Shipped', 'Delivered', 'Cancelled')),
        order_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        total_cost NUMERIC(12,2) NOT NULL
      );
    `);
    console.log("✓ distributor_orders table ready with precise relational schemas.");

    // 6. Create ai_restocking_notifications table
    await client.query(`
      CREATE TABLE IF NOT EXISTS ai_restocking_notifications (
        notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        vendor_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        alert_type VARCHAR(50) NOT NULL CONSTRAINT chk_alert_type CHECK (alert_type IN ('Low_Stock', 'Out_of_Stock')),
        product_id INTEGER REFERENCES products(product_id) ON DELETE CASCADE,
        ai_predicted_restock_date TIMESTAMP WITH TIME ZONE,
        is_read BOOLEAN NOT NULL DEFAULT FALSE
      );
    `);
    console.log("✓ ai_restocking_notifications table ready with alert_type and is_read states.");

    // 7. Create product_trends table
    await client.query(`
      CREATE TABLE IF NOT EXISTS product_trends (
        product_id INTEGER PRIMARY KEY REFERENCES products(product_id) ON DELETE CASCADE,
        product_sales_velocity NUMERIC(8,2) NOT NULL DEFAULT 0.00,
        times_demanded_count INTEGER NOT NULL DEFAULT 0,
        trending_rank INTEGER,
        peak_sales_season VARCHAR(100),
        high_margin_operator_flag BOOLEAN NOT NULL DEFAULT FALSE
      );
    `);
    console.log("✓ product_trends table ready for Trend Analysis.");

    // 8. Create profit_loss_tracking table
    await client.query(`
      CREATE TABLE IF NOT EXISTS profit_loss_tracking (
        transaction_id VARCHAR(100) PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
        cost_price_per_unit NUMERIC(10,2) NOT NULL DEFAULT 0.00,
        selling_price_per_unit NUMERIC(10,2) NOT NULL DEFAULT 0.00,
        net_profit_margin NUMERIC(10,2) NOT NULL DEFAULT 0.00,
        total_expense NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        total_revenue NUMERIC(12,2) NOT NULL DEFAULT 0.00
      );
    `);
    console.log("✓ profit_loss_tracking table ready for Profit & Loss Tracking.");

    // 9. Create sales_reports table
    await client.query(`
      CREATE TABLE IF NOT EXISTS sales_reports (
        report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        report_type VARCHAR(50) NOT NULL CONSTRAINT chk_report_type CHECK (report_type IN ('Weekly', 'Monthly', 'Yearly', 'Custom')),
        total_sales_volume INTEGER NOT NULL DEFAULT 0,
        gross_revenue NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL
      );
    `);
    console.log("✓ sales_reports table ready for Sales Reports.");

    // 10. Create invoices table
    await client.query(`
      CREATE TABLE IF NOT EXISTS invoices (
        invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        tax_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
        discount_applied NUMERIC(10,2) NOT NULL DEFAULT 0.00,
        final_payable_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
        ai_verification_status VARCHAR(50) NOT NULL DEFAULT 'Verified' CONSTRAINT chk_ai_verification_status CHECK (ai_verification_status IN ('Verified', 'Flagged', 'Mismatch')),
        ai_error_logs TEXT
      );
    `);
    console.log("✓ invoices table ready for Invoice Billing & AI Checking.");

    // 11. Create telegram_customers table
    await client.query(`
      CREATE TABLE IF NOT EXISTS telegram_customers (
        customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        telegram_chat_id VARCHAR(100) NOT NULL,
        opt_in_status BOOLEAN NOT NULL DEFAULT TRUE,
        last_message_sent_timestamp TIMESTAMP WITH TIME ZONE,
        message_delivery_status VARCHAR(50) CONSTRAINT chk_message_delivery_status CHECK (message_delivery_status IN ('Sent', 'Delivered', 'Failed'))
      );
    `);
    console.log("✓ telegram_customers table ready.");

    // 12. Create product_deliveries table
    await client.query(`
      CREATE TABLE IF NOT EXISTS product_deliveries (
        delivery_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        distributor_order_id INTEGER REFERENCES distributor_orders(distributor_order_id) ON DELETE CASCADE,
        tracking_number VARCHAR(100) NOT NULL UNIQUE,
        shipping_carrier VARCHAR(100) NOT NULL,
        estimated_delivery_time TIMESTAMP WITH TIME ZONE,
        actual_delivery_time TIMESTAMP WITH TIME ZONE,
        current_gps_coordinates VARCHAR(100)
      );
    `);
    console.log("✓ product_deliveries table ready.");

    // 13. Create payment_transactions table
    await client.query(`
      CREATE TABLE IF NOT EXISTS payment_transactions (
        payment_gateway_transaction_id VARCHAR(100) PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        payment_method VARCHAR(50) NOT NULL CONSTRAINT chk_payment_method CHECK (payment_method IN ('UPI', 'Card', 'NetBanking', 'Cash')),
        payment_status VARCHAR(50) NOT NULL CONSTRAINT chk_payment_status CHECK (payment_status IN ('Success', 'Failed', 'Processing', 'Refunded')),
        gateway_response_payload JSONB NOT NULL,
        amount NUMERIC(10,2) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log("✓ payment_transactions table ready.");

    // 14. Create telegram_vendor_communities table
    await client.query(`
      CREATE TABLE IF NOT EXISTS telegram_vendor_communities (
        vendor_telegram_id VARCHAR(100) PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        community_group_id VARCHAR(100) NOT NULL,
        community_role VARCHAR(50) NOT NULL CONSTRAINT chk_community_role CHECK (community_role IN ('Admin', 'Member', 'Moderator')),
        join_date DATE NOT NULL DEFAULT CURRENT_DATE,
        community_ban_status BOOLEAN NOT NULL DEFAULT FALSE
      );
    `);
    console.log("✓ telegram_vendor_communities table ready.");

    // 15. Create chatbot_sessions table
    await client.query(`
      CREATE TABLE IF NOT EXISTS chatbot_sessions (
        session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        store_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        user_query_text TEXT NOT NULL,
        ai_response_text TEXT NOT NULL,
        intent_classification VARCHAR(100) NOT NULL,
        user_satisfaction_rating INTEGER CONSTRAINT chk_user_satisfaction CHECK (user_satisfaction_rating BETWEEN 1 AND 5),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log("✓ chatbot_sessions table ready.");

    // 16. Create live_auctions table
    await client.query(`
      CREATE TABLE IF NOT EXISTS live_auctions (
        auction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        distributor_id INTEGER REFERENCES distributors(distributor_id) ON DELETE CASCADE,
        auction_item_id INTEGER REFERENCES products(product_id) ON DELETE CASCADE,
        starting_bid_price NUMERIC(10,2) NOT NULL,
        current_highest_bid NUMERIC(10,2) NOT NULL,
        highest_bidder_vendor_id INTEGER REFERENCES stores(store_id) ON DELETE CASCADE,
        auction_countdown_end TIMESTAMP WITH TIME ZONE NOT NULL,
        live_status BOOLEAN NOT NULL DEFAULT TRUE
      );
    `);
    console.log("✓ live_auctions table ready.");

    // Seed default distributors
    const prepopDistributors = [
      ["Apex Logistics", "apex@logistics.com"],
      ["Nova Supply Chain", "nova@supplychain.com"],
      ["Quantum Core Wholesalers", "quantum@wholesalers.com"]
    ];
    for (const dist of prepopDistributors) {
      await client.query(
        "INSERT INTO distributors (distributor_name, contact_email) VALUES ($1, $2) ON CONFLICT (distributor_name) DO NOTHING;",
        dist
      );
    }
    console.log("✓ Prepopulated default distributors.");

    // Prepopulate default records scoped for EVERY active store in the database
    const storesResult = await client.query("SELECT store_id, store_name FROM stores;");
    const activeStores = storesResult.rows;

    for (const store of activeStores) {
      const sId = store.store_id;
      
      // Update any null store_id items in existing database to the first active store to prevent breaking constraints
      await client.query("UPDATE products SET store_id = $1 WHERE store_id IS NULL;", [sId]);
      await client.query("UPDATE transactions SET store_id = $1 WHERE store_id IS NULL;", [sId]);

      // Prepopulate Products scoped to this store using exact columns
      const productCheck = await client.query("SELECT COUNT(*) FROM products WHERE store_id = $1;", [sId]);
      if (parseInt(productCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default products for store: "${store.store_name}" (ID: ${sId})...`);
        // [name, unit_price, stock, category, description, images, photos, cost_price]
        const prepopProducts = [
          ["Quantum Processor Cores", 149.99, 18, "Processors", "High-performance processing unit designed for standard sub-grid calculations.", [], [], 85.00],
          ["Aetheric Flux Diodes", 24.50, 3, "Hardware", "Basic component designed to modulate reverse flow within high-voltage sub-modules.", [], [], 12.00],
          ["Torus Magnetic Induction Rings", 89.00, 24, "Coils", "Core component utilized in generating dynamic sub-second electromagnetic fields.", [], [], 42.00],
          ["Glass Graphene Capacitors", 15.75, 0, "Components", "Capacitor node using advanced layered graphene sheets to hold micro-level charge levels.", [], [], 7.50]
        ];
        for (const prod of prepopProducts) {
          await client.query(
            "INSERT INTO products (store_id, product_name, unit_price, current_stock_level, category, description, images, photos, cost_price) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING;",
            [sId, ...prod]
          );
        }
      }

      // Prepopulate Transactions scoped to this store (with product links for P&L)
      const txCheck = await client.query("SELECT COUNT(*) FROM transactions WHERE store_id = $1;", [sId]);
      if (parseInt(txCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default transactions for store: "${store.store_name}" (ID: ${sId})...`);
        // Fetch product IDs for linking
        const storeProdRows = await client.query("SELECT product_id, product_name, unit_price, cost_price FROM products WHERE store_id = $1;", [sId]);
        const prodMap = {};
        storeProdRows.rows.forEach(p => { prodMap[p.product_name] = p; });

        // [tx_id, client, amount, method, status, productName, quantity]
        const prepopTx = [
          [`TX_8820_${sId}`, "Alice Cooper", 149.99, "Credit Node", "Cleared", "Quantum Processor Cores", 1],
          [`TX_5541_${sId}`, "Quantum Devs Ltd", 890.00, "Direct Bank", "Cleared", "Torus Magnetic Induction Rings", 10],
          [`TX_1092_${sId}`, "Bob Vance", 24.50, "Merchant Pay", "Cleared", "Aetheric Flux Diodes", 1]
        ];
        for (const tx of prepopTx) {
          const linkedProd = prodMap[tx[5]];
          const pId = linkedProd ? linkedProd.product_id : null;
          const costPrice = linkedProd ? parseFloat(linkedProd.cost_price || 0) : 0;
          const sellingPrice = linkedProd ? parseFloat(linkedProd.unit_price) : parseFloat(tx[2]);
          const qty = tx[6];
          const totalExpense = costPrice * qty;
          const totalRevenue = sellingPrice * qty;
          const margin = totalRevenue > 0 ? ((totalRevenue - totalExpense) / totalRevenue * 100) : 0;

          await client.query(
            "INSERT INTO transactions (transaction_id, store_id, client_name, amount, method, status, product_id, quantity) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT DO NOTHING;",
            [tx[0], sId, tx[1], tx[2], tx[3], tx[4], pId, qty]
          );
          
          await client.query(
            "INSERT INTO profit_loss_tracking (transaction_id, cost_price_per_unit, selling_price_per_unit, net_profit_margin, total_expense, total_revenue) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING;",
            [tx[0], costPrice, sellingPrice, parseFloat(margin.toFixed(2)), totalExpense, totalRevenue]
          );
        }
      }

      // Prepopulate Distributor Orders scoped to this store
      const distCheck = await client.query("SELECT distributor_id FROM distributors LIMIT 1;");
      if (distCheck.rows.length > 0) {
        const dId = distCheck.rows[0].distributor_id;
        const ordCheck = await client.query("SELECT COUNT(*) FROM distributor_orders WHERE store_id = $1;", [sId]);
        if (parseInt(ordCheck.rows[0].count) === 0) {
          console.log(`Prepopulating default distributor orders for store: "${store.store_name}" (ID: ${sId})...`);
          const itemsPayload = JSON.stringify([
            { product_name: "Aetheric Flux Diodes", quantity: 15 },
            { product_name: "Torus Magnetic Induction Rings", quantity: 5 }
          ]);
          await client.query(
            "INSERT INTO distributor_orders (store_id, distributor_id, ordered_items_list, order_status, total_cost) VALUES ($1, $2, $3, $4, $5);",
            [sId, dId, itemsPayload, 'Delivered', 812.50]
          );
        }
      }

      // Prepopulate AI Restocking Notifications scoped to this store
      const notifCheck = await client.query("SELECT COUNT(*) FROM ai_restocking_notifications WHERE vendor_id = $1;", [sId]);
      if (parseInt(notifCheck.rows[0].count) === 0) {
        // Fetch a low stock item
        const lowStockRes = await client.query("SELECT product_id FROM products WHERE store_id = $1 AND current_stock_level <= minimum_stock_threshold LIMIT 1;", [sId]);
        if (lowStockRes.rows.length > 0) {
          console.log(`Prepopulating default AI restocking notifications for store: "${store.store_name}" (ID: ${sId})...`);
          const pId = lowStockRes.rows[0].product_id;
          const predictedDate = new Date();
          predictedDate.setDate(predictedDate.getDate() + 3); // Predictions 3 days out
          await client.query(
            "INSERT INTO ai_restocking_notifications (vendor_id, alert_type, product_id, ai_predicted_restock_date, is_read) VALUES ($1, $2, $3, $4, $5);",
            [sId, 'Low_Stock', pId, predictedDate, false]
          );
        }
      }

      // Prepopulate Product Trends scoped to products in this store
      console.log(`Prepopulating default product trends for store: "${store.store_name}" (ID: ${sId})...`);
      const storeProds = await client.query("SELECT product_id, product_name FROM products WHERE store_id = $1;", [sId]);
      for (const prod of storeProds.rows) {
        const pId = prod.product_id;
        const pName = prod.product_name;
        
        let velocity = 0.00;
        let demand = 0;
        let rank = 10;
        let peak = "All-Season";
        let isHighMargin = false;

        if (pName.includes("Torus Magnetic Induction Rings")) {
          velocity = 38.90;
          demand = 210;
          rank = 1;
          peak = "Summer";
          isHighMargin = true;
        } else if (pName.includes("Quantum Processor Cores")) {
          velocity = 28.40;
          demand = 142;
          rank = 2;
          peak = "Autumn";
          isHighMargin = true;
        } else if (pName.includes("Aetheric Flux Diodes")) {
          velocity = 12.50;
          demand = 64;
          rank = 4;
          peak = "Spring";
          isHighMargin = false;
        } else if (pName.includes("Glass Graphene Capacitors")) {
          velocity = 5.20;
          demand = 18;
          rank = 6;
          peak = "Winter";
          isHighMargin = false;
        }

        await client.query(`
          INSERT INTO product_trends (product_id, product_sales_velocity, times_demanded_count, trending_rank, peak_sales_season, high_margin_operator_flag)
          VALUES ($1, $2, $3, $4, $5, $6)
          ON CONFLICT (product_id) DO UPDATE 
          SET product_sales_velocity = EXCLUDED.product_sales_velocity,
              times_demanded_count = EXCLUDED.times_demanded_count,
              trending_rank = EXCLUDED.trending_rank,
              peak_sales_season = EXCLUDED.peak_sales_season,
              high_margin_operator_flag = EXCLUDED.high_margin_operator_flag;
        `, [pId, velocity, demand, rank, peak, isHighMargin]);
      }

      // Prepopulate Sales Reports scoped to this store
      const repCheck = await client.query("SELECT COUNT(*) FROM sales_reports WHERE store_id = $1;", [sId]);
      if (parseInt(repCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default sales reports for store: "${store.store_name}" (ID: ${sId})...`);
        const today = new Date();
        
        // 1. Weekly Report (7 days ago to today)
        const weeklyStart = new Date();
        weeklyStart.setDate(today.getDate() - 7);
        await client.query(`
          INSERT INTO sales_reports (store_id, report_type, total_sales_volume, gross_revenue, start_date, end_date)
          VALUES ($1, 'Weekly', 35, 1190.00, $2, $3);
        `, [sId, weeklyStart, today]);

        // 2. Monthly Report (30 days ago to today)
        const monthlyStart = new Date();
        monthlyStart.setDate(today.getDate() - 30);
        await client.query(`
          INSERT INTO sales_reports (store_id, report_type, total_sales_volume, gross_revenue, start_date, end_date)
          VALUES ($1, 'Monthly', 124, 4850.00, $2, $3);
        `, [sId, monthlyStart, today]);

        // 3. Yearly Report (365 days ago to today)
        const yearlyStart = new Date();
        yearlyStart.setDate(today.getDate() - 365);
        await client.query(`
          INSERT INTO sales_reports (store_id, report_type, total_sales_volume, gross_revenue, start_date, end_date)
          VALUES ($1, 'Yearly', 1450, 54200.00, $2, $3);
        `, [sId, yearlyStart, today]);
      }

      // Prepopulate Invoices scoped to this store
      const invCheck = await client.query("SELECT COUNT(*) FROM invoices WHERE store_id = $1;", [sId]);
      if (parseInt(invCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default audited invoices for store: "${store.store_name}" (ID: ${sId})...`);
        await client.query(`
          INSERT INTO invoices (store_id, tax_amount, discount_applied, final_payable_amount, ai_verification_status, ai_error_logs)
          VALUES 
            ($1, 15.00, 0.00, 165.00, 'Verified', '✓ Billing structure compliance check passed. No anomalies detected.'),
            ($1, 85.00, 50.00, 885.00, 'Verified', '✓ Volume purchase coupon verified. Auditor clearance cleared.');
        `, [sId]);
      }

      // Prepopulate Telegram Customers scoped to this store
      const customerCheck = await client.query("SELECT COUNT(*) FROM telegram_customers WHERE store_id = $1;", [sId]);
      if (parseInt(customerCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default telegram customers for store ID ${sId}...`);
        await client.query(`
          INSERT INTO telegram_customers (store_id, telegram_chat_id, opt_in_status, last_message_sent_timestamp, message_delivery_status)
          VALUES 
            ($1, 'CHAT_ID_8801', TRUE, CURRENT_TIMESTAMP - INTERVAL '1 hour', 'Delivered'),
            ($1, 'CHAT_ID_4402', TRUE, CURRENT_TIMESTAMP - INTERVAL '2 hours', 'Sent'),
            ($1, 'CHAT_ID_1092', FALSE, NULL, NULL);
        `, [sId]);
      }

      // Prepopulate Product Deliveries scoped to this store
      const deliveryCheck = await client.query("SELECT COUNT(*) FROM product_deliveries WHERE store_id = $1;", [sId]);
      if (parseInt(deliveryCheck.rows[0].count) === 0) {
        const ordRes = await client.query("SELECT distributor_order_id FROM distributor_orders WHERE store_id = $1 LIMIT 1;", [sId]);
        if (ordRes.rows.length > 0) {
          const ordId = ordRes.rows[0].distributor_order_id;
          console.log(`Prepopulating default product deliveries for store ID ${sId}...`);
          const estDelivery = new Date();
          estDelivery.setHours(estDelivery.getHours() + 4);
          await client.query(`
            INSERT INTO product_deliveries (store_id, distributor_order_id, tracking_number, shipping_carrier, estimated_delivery_time, actual_delivery_time, current_gps_coordinates)
            VALUES ($1, $2, $3, 'Apex FastFreight', $4, NULL, '37.7749,-122.4194');
          `, [sId, ordId, `TRK-90082-VV-${sId}`, estDelivery]);
        }
      }

      // Prepopulate Payment Transactions scoped to this store
      const payCheck = await client.query("SELECT COUNT(*) FROM payment_transactions WHERE store_id = $1;", [sId]);
      if (parseInt(payCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default payment transactions for store ID ${sId}...`);
        await client.query(`
          INSERT INTO payment_transactions (payment_gateway_transaction_id, store_id, payment_method, payment_status, gateway_response_payload, amount)
          VALUES 
            ($1, $2, 'Card', 'Success', '{"gateway": "Stripe", "charge_id": "ch_3992", "card_brand": "Visa", "auth_code": "099281"}', 149.99),
            ($3, $2, 'UPI', 'Success', '{"gateway": "Razorpay", "payment_id": "pay_88201", "vpa": "alice@upi", "bank_ref": "882019"}', 24.50),
            ($4, $2, 'NetBanking', 'Failed', '{"gateway": "Stripe", "error_code": "insufficient_funds", "decline_reason": "Limit exceeded"}', 890.00);
        `, [`PAY_STRIPE_${sId}_1`, sId, `PAY_UPI_${sId}_2`, `PAY_STRIPE_${sId}_3`]);
      }

      // Prepopulate Telegram Vendor Communities scoped to this store
      const commCheck = await client.query("SELECT COUNT(*) FROM telegram_vendor_communities WHERE store_id = $1;", [sId]);
      if (parseInt(commCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default telegram vendor communities for store ID ${sId}...`);
        await client.query(`
          INSERT INTO telegram_vendor_communities (vendor_telegram_id, store_id, community_group_id, community_role, join_date, community_ban_status)
          VALUES 
            ($1, $2, 'GROUP_COLLECTIVE_01', 'Admin', CURRENT_DATE - 30, FALSE),
            ($3, $2, 'GROUP_COLLECTIVE_01', 'Member', CURRENT_DATE - 15, FALSE);
        `, [`TEL_VEND_${sId}_A`, sId, `TEL_VEND_${sId}_B`]);
      }

      // Prepopulate Chatbot Sessions scoped to this store
      const chatSessCheck = await client.query("SELECT COUNT(*) FROM chatbot_sessions WHERE store_id = $1;", [sId]);
      if (parseInt(chatSessCheck.rows[0].count) === 0) {
        console.log(`Prepopulating default chatbot sessions for store ID ${sId}...`);
        await client.query(`
          INSERT INTO chatbot_sessions (store_id, user_query_text, ai_response_text, intent_classification, user_satisfaction_rating)
          VALUES 
            ($1, 'How do I check my monthly profit margin?', 'Your net monthly profit stands at $1,190.00 with a 72.4% net margin.', 'Sales', 5),
            ($1, 'Show me empty stock levels.', 'Your product "Glass Graphene Capacitors" has 0 units left.', 'Restock', 4);
        `, [sId]);
      }

      // Prepopulate Live Auctions
      const aucCheck = await client.query("SELECT COUNT(*) FROM live_auctions;");
      if (parseInt(aucCheck.rows[0].count) === 0) {
        const prodRes = await client.query("SELECT product_id, unit_price FROM products WHERE store_id = $1 LIMIT 1;", [sId]);
        const distRes = await client.query("SELECT distributor_id FROM distributors LIMIT 1;");
        if (prodRes.rows.length > 0 && distRes.rows.length > 0) {
          console.log(`Prepopulating default live auctions...`);
          const pId = prodRes.rows[0].product_id;
          const price = parseFloat(prodRes.rows[0].unit_price);
          const dId = distRes.rows[0].distributor_id;
          const endLimit = new Date();
          endLimit.setHours(endLimit.getHours() + 2);
          await client.query(`
            INSERT INTO live_auctions (distributor_id, auction_item_id, starting_bid_price, current_highest_bid, highest_bidder_vendor_id, auction_countdown_end, live_status)
            VALUES ($1, $2, $3, $4, $5, $6, TRUE);
          `, [dId, pId, price * 0.5, price * 0.8, sId, endLimit]);
        }
      }
    }

    console.log("🎉 Database schema multi-tenancy scoping successfully initialized!");

  } catch (err) {
    console.error("❌ Database scoping migration exception:", err.message);
  } finally {
    if (client) client.release();
    await pool.end();
  }
}

initDatabase();
