import pg from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const connectionString = process.env.DATABASE_URL;

console.log("Connecting to Neon PostgreSQL database...");
console.log("Connection Source Host:", process.env.PGHOST || "Neon Tech");

const pool = new pg.Pool({
  connectionString,
  ssl: {
    rejectUnauthorized: false
  }
});

async function runCheck() {
  let client;
  try {
    client = await pool.connect();
    console.log("✓ Successfully connected to Neon PostgreSQL!");

    // Check if stores table exists
    const tableCheck = await client.query(`
      SELECT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'stores'
      );
    `);
    
    const tableExists = tableCheck.rows[0].exists;
    console.log("Stores Table Exists:", tableExists ? "YES" : "NO");

    if (!tableExists) {
      console.log("Initializing stores table...");
      await client.query(`
        CREATE TABLE IF NOT EXISTS stores (
          store_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          store_name VARCHAR(100) NOT NULL UNIQUE,
          CONSTRAINT chk_store_name_length CHECK (char_length(TRIM(store_name)) >= 2),
          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
      `);
      console.log("✓ stores table created successfully!");
    }

    // Query stores table content
    const res = await client.query("SELECT * FROM stores ORDER BY store_id ASC;");
    console.log(`\n--- Active Store Records in database (${res.rows.length} found) ---`);
    console.table(res.rows);
    
  } catch (err) {
    console.error("❌ Database query error:", err.message);
  } finally {
    if (client) client.release();
    await pool.end();
  }
}

runCheck();
