-- DDL Script to create the stores table in Neon PostgreSQL
-- Ensures store_id auto-increments and store_name is stored with validation constraints

CREATE TABLE IF NOT EXISTS stores (
    -- Auto-incrementing unique identifier
    store_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Store name validation: maximum length 100, must be unique and non-null
    store_name VARCHAR(100) NOT NULL UNIQUE,
    
    -- Prevent empty strings or single space names
    CONSTRAINT chk_store_name_length CHECK (char_length(TRIM(store_name)) >= 2),
    
    -- Creation timestamp
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
